export class NotificationModel {
  
    public _id!: string; // generated by mongoDB
    public senderName!: string;
    public senderSurname!: string;
    public timeSent!: Date;
    public typeNotification!: number;
    public title!:string;
    public createdAt!: Date; // generated by mongoDB
    public updatedAt!: Date; // generated by mongoDB
    constructor(model?: any) {
      Object.assign(this, model);
    }
  
  }
