export class PatientModel {
  
    public _id!: string; // generated by mongoDB
    public name!: string;
    public surname!: string;
    public age!: number;
    public weight!: number;
    public height!: number;
    public emergencyName!: string;
    public emergencyPhone!: string;
    public emergencyEmail!: string;
    public cameraUrl!: string;
    public createdAt!: Date; // generated by mongoDB
    public updatedAt!: Date; // generated by mongoDB
    constructor(model?: any) {
      Object.assign(this, model);
    }
  
  }
