export class RoutineModel {
    public patient!:string;
    public _id!: string; // generated by mongoDB
    public title!: string;
    public startTime!: Date;
    public endTime?: Date;
    public reqiresCaretaker!: boolean;
    public type!: string;
    public description!: string;
    public completed!: boolean;
    public createdAt!: Date; // generated by mongoDB
    public updatedAt!: Date; // generated by mongoDB
    constructor(model?: any) {
      Object.assign(this, model);
    }
  
  }

