export class VitalsModel {
    public _id!: string; // generated by mongoDB
    public name!: string;
    public surname!: string;
    public status!: string;
    public heartRate!: number;
    public spo2!: number;
    public stress!: string;
    public createdAt!: Date; // generated by mongoDB
    public updatedAt!: Date; // generated by mongoDB
    constructor(model?: any) {
      Object.assign(this, model);
    }
  
  }
